//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Tracker_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime__and_Cartoons
    {
        public double Completed_Anime___Cartoon_ID { get; set; }
        public string Completed_Anime_Cartoons { get; set; }
        public string Recommended { get; set; }
        public string F4 { get; set; }
        public string F5 { get; set; }
    }
}
