//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Tracker_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Completed_Manga_and_Manwah
    {
        public double Completed_Manga___Manwah_ID { get; set; }
        public string Completed_Manga { get; set; }
        public string Recommend { get; set; }
    }
}
