//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Tracker_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Live_Action_TV_Shows
    {
        public int TV_Show_ID { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public string Recommend { get; set; }
        public string Year { get; set; }
        public string Download { get; set; }
        public string Need_to_watch { get; set; }
    }
}
