//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Tracker_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manga_and_Manwah
    {
        public double Manga___Manwah_ID { get; set; }
        public string Current_Manga { get; set; }
        public Nullable<double> Last_Chapter_Read { get; set; }
    }
}
