//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Tracker_App.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animated_Movies> Animated_Movies { get; set; }
        public virtual DbSet<Anime__and_Cartoons> Anime__and_Cartoons { get; set; }
        public virtual DbSet<Completed_Manga_and_Manwah> Completed_Manga_and_Manwah { get; set; }
        public virtual DbSet<Current_Anime_and_Cartoons> Current_Anime_and_Cartoons { get; set; }
        public virtual DbSet<Live_Action_Movies> Live_Action_Movies { get; set; }
        public virtual DbSet<Live_Action_TV_Shows> Live_Action_TV_Shows { get; set; }
        public virtual DbSet<Manga_and_Manwah> Manga_and_Manwah { get; set; }
        public virtual DbSet<Video_Game> Video_Game { get; set; }
    }
}
