//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Tracker_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video_Games
    {
        public int Video_Game_ID { get; set; }
        public string Name { get; set; }
        public string Platform { get; set; }
        public string Recommendation { get; set; }
    }
}
